### ISSUE TITLE
[Feature] Make a map function to scale inputs 

### ISSUE THREAD

**Issue by Armagedon13** [Matthew-J-Green/dvDirectInput#1]
This make any input to scale to the requirements of input of 16 bits

Re-maps a number from one range to another. That is, a value of fromLow would get mapped to toLow, a value of fromHigh to toHigh, values in-between to values in-between, etc.

Does not constrain values to within the range, because out-of-range values are sometimes intended and useful. The constrain() function may be used either before or after this function, if limits to the ranges are desired.

Note that the "lower bounds" of either range may be larger or smaller than the "upper bounds" so the map() function may be used to reverse a range of numbers, for example

y = map(x, 1, 50, 50, 1);

The function also handles negative numbers well, so that this example

y = map(x, 1, 50, 50, -100);

is also valid and works well.

The map() function uses integer math so will not generate fractions, when the math might indicate that it should do so. Fractional remainders are truncated, and are not rounded or averaged.

map(value, fromLow, fromHigh, toLow, toHigh)

Parameters
value: the number to map.
fromLow: the lower bound of the value’s current range.
fromHigh: the upper bound of the value’s current range.
toLow: the lower bound of the value’s target range.
toHigh: the upper bound of the value’s target range.

For the mathematically inclined, here’s the whole function

```
long map(long x, long in_min, long in_max, long out_min, long out_max) {
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
```

**Comment by Matthew-J-Green** [comment]
The inputs get normalised in the Input struct.
Ill change the mapping from dividing by 16bit max value to this function.

For my own knowledge, are you having issues with the Input ranges? I'm curious if all devices use the same range or if its based off the capabilites of the device such as if they are using ADCs with certain resolutions and don't scale it to 16 bits.

I theory I might be able to get the axis range from DirectInput and use that to run the normalisation

**Comment by Armagedon13** [comment]
Well, if you use a joystick with a microcontroller like arduino leonardo, stm32, esp32, raspberry pi pico, they don't have a analog input with so much resolution, neither the joysticks.
arduino 10 bits, stm32, 12 bits, esp32 12 bits, raspberry pi pico 16 bits but very noisy. the idea of have map funtion is if you have any input with different resolution you always have a 16 bits scalated. 
 Thats because i read the readme in limitations:

> This mod assumes the device outputs its axis with values between 0 and 65535. It's unclear if all devices use this range.

maybe you can make the reverser to a digital input divided by 3 (value of analog(65535) / 3) example:

step 1 -> 21.845
step 2 -> 32767
step 3 -> 65535

that make a analog input to a better controllers like brakes, and step inputs digitals(you can use a rotary switch to simulate systems like lights, wipers, etc)

sorry if this is too much text or stupid i'm getting excited to make a controller to DV

some libraries
[Arduino leonardo joystick library](https://github.com/MHeironimus/ArduinoJoystickLibrary/tree/master)
[Stm32 joystick](https://github.com/FreeJoy-Team/FreeJoy)
[Rp2040 Joystick](https://github.com/benjaminaigner/Joystick)

**Comment by Matthew-J-Green** [comment]
I've had a look around at all the reported devices properties in SharpDX.DirectInput and there is one which should let you set or get the range that the inputs support. But this just throws an error. 

Im leaning towards SharpDX.DirectInput just scaling all the inputs to a 16 bit range regardless of what the actual device capabilities are.
It wouldnt make sense for there to be no way of getting and setting the input ranges supported by the device and have the user manually do it.

If it turns out im wrong I can easily add this functionality in.

**Comment by Matthew-J-Green** [comment]
The actual information is over in joystick.GetObjectPropertiesById(joystick.GetObjects()[0].ObjectId)

where LogicalRange, PhysicalRange and Range exist.
These turn up like:

[Info   :dvDirectInput] LogicalRange: 0, 4095
[Info   :dvDirectInput] PhysicalRange: 0, 4095
[Info   :dvDirectInput] Range: 0, 65535

so it seems that although devices give a small range its is scaled to an 16 bit value by default by DirectInput

Closing for now as it doesnt appear that it will ever be an issue
