### ISSUE TITLE
Mod not working since Build 96

### ISSUE THREAD

**Issue by g1llez** [Matthew-J-Green/dvDirectInput#15]
The Mod loads properly, detect the signal from the input as we can see in the debug GUI, but the control are not working in the game.

**Comment by CODEYXone** [comment]
Can confirm. dvDirectInput v0.5.2 doesn't seem to work with DV Build 96.

**Comment by Matthew-J-Green** [comment]
I just tested 0.5.2 and it still works. Check that your inputs haven't reset themselves. You can also try deleting settings.xml in "Derail Valley/Mods/dvDirectInput"

Try with only this mod enabled too.

If none of that works I'll try adding extra debug to find where the issue is

**Comment by CODEYXone** [comment]
@Matthew-J-Green Deleting the settings.xml fixed it right away, thanks!

I guess it's only a problem for any installations done in Build 95 that got brought over to the new Build 96. New installations should work fine.

**Comment by g1llez** [comment]
Confirmed working, for me with was a mixte of another Mods causing the issue and lost some configuration from 95 to 96!
